version: '3.8'
services:

  fontend:
    build: 
      context: ./vnua-test
      dockerfile: Dockerfile
    ports:
      - "8088:8099"
    depends_on:
      - backend

  backend:
    build: 
      context: ./VNUA_TEST
      dockerfile: Dockerfile
    depends_on:
      - postgresql
    ports:
      - "3005:3000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/VNUA_EXAM
      - SPRING_DATASOURCE_USERNAME=vuvanhoang
      - SPRING_DATASOURCE_PASSWORD=Hoanglam06112003@
      - SPRING_PROFILES_ACTIVE=prod

  postgresql:
    image: postgres:14
    environment:
      POSTGRES_DB: vuvanhoang
      POSTGRES_PASSWORD: Hoanglam06112003@
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: