version: '3.8'
services:

  fontend:
    build: 
      context: ./vnua-test
      dockerfile: Dockerfile
    ports:
      - "3005:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ./VNUA_TEST
      dockerfile: Dockerfile
    # depends_on:
    #   - postgresql
    ports:
      - "8088:8099"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://172.17.0.1:5432/vnua_exam
      - SPRING_DATASOURCE_USERNAME=vuvanhoang
      - SPRING_DATASOURCE_PASSWORD=Hoanglam06112003@
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  # postgresql:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: VNUA_TEST
  #     POSTGRES_PASSWORD: Hoanglam06112003@
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge