version: '3.8'
services:
  postgresql:
    image: postgres:15
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./VNUA_TEST
      dockerfile: Dockerfile
    depends_on:
      - postgresql
    ports:
      - "8088:8099"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/yourdbname
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=yourpassword

  frontend:
    build: 
      context: ./vnua-test
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres-data: