spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://172.17.0.1:5432/vnua_exam
    username: vuvanhoang
    password: Hoanglam06112003@
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 450
      connection-timeout: 10000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 200 #minimum number of idle connections maintained by HikariCP in a connection pool
      idle-timeout: 10000 #maximum idle time for connection

  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: create

server:
  port: 8099
  servlet:
    context-path: /api/v1

logging:
  level:
    org:
      springframework:
        security: INFO

security:
  jwt:
    token:
      secret-key: "khgfjdkhg45345dj#$%&*(@#$@#$fhgkdhguytit4yfdss34yt4234}ơ]ơ]ơp]-=0=-0=-09hrughkdjfhgkfdhgdkfhgkddas%^$@#$2#$@#$@s2342342dfgsdgdfgdfg"
      # 1 days: 1000*60*60*24
      expiration: 86400000
      # 2 days
      refresh_expiration: 172800000

# Size of chunk to read excel, csv file
size:
  chunk: 100
  batch: 100